# Generated by Django 2.2 on 2021-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
