# Generated by Django 2.2 on 2021-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0002_auto_20210427_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
