# Generated by Django 2.2 on 2021-04-26 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
                ('target', models.IntegerField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(related_name='newsletters', to='tags_app.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
