# Generated by Django 2.2 on 2021-05-02 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='members',
            field=models.ManyToManyField(related_name='editable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletters',
            name='tags',
            field=models.ManyToManyField(related_name='newsletters', to='tags_app.Tag'),
        ),
        migrations.AddField(
            model_name='newsletters',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletters',
            name='users',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletters',
            name='voters',
            field=models.ManyToManyField(related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
