# Generated by Django 2.2 on 2021-04-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter_app', '0002_newsletters_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='tags',
            field=models.ManyToManyField(related_name='newsletters', to='tags_app.Tag'),
        ),
        migrations.AddField(
            model_name='newsletters',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
